
version: 2

models:
  - name: raw_data
    description: "raw_data as a view"
    columns:
      - name: row_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: stg_data
    description: |
      Transformation procedures: \
      - Add column: category_id using generate_surrogate_key based off of category and sub_category
    columns:
      - name: customer_id
        descrption: "Will act as the primary key for the customer dim table downstream"
        tests:
          - unique
          - not_null
      - name: order_id
        descrption: "Will act as the primary key for the order dim table downstream"
        tests:
          - unique
          - not_null
      - name: product_id
        descrption: "Will act as the primary key for the customer dim table downstream"
        tests:
          - unique
          - not_null
      - name: category_id
        descrption: "Will act as the primary key for the customer dim table downstream"
        tests:
          - unique
          - not_null